# -*- coding: utf-8 -*-
"""Script Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whHIMdoi8_0SNYnYbId-nb8vuFvtLPwW

1º Sessão
"""

#Blocos de comando

print("Vamos aprender Python")

print("Bem vindo ao curso de python!")

"""Bora aprender mais de python"""

# Isso é um comentário de linha

'''
Comentário em bloco
'''
print('Olá pessoal \n Bora estudar')

# Operadores matemáticos
4 + 5

2 ** 2 
# Exponenciação

9 / 10

# Resto da divisão 
3 % 2

# Divisão de chão
3 // 4

# Divisão normal 
3 / 4

# priorização 
2+2*10-5

# priorização 2
(10*2) - 5

(5**3)/2+10



"""Variáveis

"""

# Variáveis
Nome = 'Aironys'

Nome

print(Nome)

sobrenome = 'Garrido'

print(sobrenome)

# Variáveis de Texto
Var_Texto = "Seja Bem vindo"
texto2 = str('Gostamos de estudar')

print(Var_Texto)

print(texto2)

# Variaveis numericas 
inteiro = 100

print(inteiro)

# Variaveis flutuanetes
flutuante1 = 25.5
flutuante2 = float(10.50)

print(flutuante1, flutuante2)

# variaveis boleanas
aprovado = True
reprovado = False

print(aprovado, reprovado)

# Lista são cadeias de valores
listas = [10,5,2,50,15,7,9]

print(listas)

lista2 = [ "Aironys", "Alice", 5, 12, 28, 10, "Jessica", "Samuel"]

print("Nomes e números \n", lista2)

# Tuplas são imutáveis
tupla = (10,100,50)

print(tupla)

tupla2=("Tupla é imutável")

print(tupla2)

# Dicionários vai ter indice e valor
dicionario = {
    'index': 'Valor ',
    'Nome': "Aironys Garrido",
    'idade': 32,
    'peso': 77,
    'Nacimento': '1990/12/05',
    'lista2': lista2,
    'Tupla': tupla
}

print(dicionario)

"""Nomeação de Variáveis

"""

# Nomeando as variáveis
Laranja, Maçã, Abacate = 1,2,3
print(1,2,3)

# Todas frutas recebem o mesmo valor
morango = uva = banana = 100
print(morango, uva, banana)

# Nomear com listas
listas_carros = ['Bmw', 'Audi', 'Tesla']
marca1, marca2, marca3 = listas_carros

print(listas_carros)

# Combinar variaveis
nome = "Aironys"
sobrenome = "Garrido"
nome_completo = (nome + ' '+ sobrenome)

print(nome_completo)

# Combinar string com inteiro
nome = "Alice"
idade = str(7) 
print(nome + ' ' + idade + ' Anos ')

# taxa de juros
investimento = 1500
juros = float(0.30)
juros_acrescido = float(1.30)

juros = (investimento * juros)
juros_acrescido = (investimento * juros_acrescido)

valor_ganho = (investimento * juros) + investimento


print(juros)
print(juros_acrescido)

print(valor_ganho)

"""Tipos de Informação"""

# Tipo de Informação

String = str('Vamos aprender python') # Palavras
Inteiro = int(50)  # Numeral 
Flutuante = float(10.5) # Numeral com pontos ou virgula
Complex = complex(1j)
lista = list(('Aironys', 'Garrido', 'Macedo')) # Vários valores em uma váriável
Tupla = tuple(('A', 'B', 'C')) # Valor não podem ser alterados
Range = range(10)
Dicionario = dict(nome = 'Aironys', age = 32) # nome e valor
Set = set(('Z', 'Y', 'Z'))
Fronzet = frozenset(('AB', 'CD', 'FG'))
Boleano = bool(10)
Bytes = bytes(15)
ByteArray = bytearray(25)
Memoryview = memoryview(bytes(5))

from datetime import datetime
Data = datetime.today().date()

print(String)
print(Inteiro)
print(Flutuante)
print(Complex)
print(lista)
print(Tupla)
print(Range)
print(Dicionario)
print(Set)
print(Fronzet)
print(Boleano)
print('São Bytes: ',Bytes)
print(bytearray)
print(Memoryview)

# Comando Round, para arredondar o valor
valor = 15.989587

print(valor)

# Arredondando o valor, com 2 casas decimais
round(valor, 2)

"""Comando Len"""

# A função len() retorna a quantidade de elementos de qualquer lista.

lista = [1,2,3,4,5,6,7,8,9,10]
dicionario = {'nome': 'Aironys', 'idade': 32}
tupla = ('A', 'B', 50)
string = ("Sempre fazendo nosso melhor")

print('Tamanho da lista',len(lista))
print('Dicionario',len(dicionario))
print('Tupla',len(tupla))
print('Tamanho da string',len(string))

"""Fatiamento de Strings"""

palavra = 'Esse ano, será sucesso para todos'
print ( type (palavra))
print(palavra)
print(palavra[0]) # pegando a primeira letra
print(palavra[-1])  # pegando a ultima letra
print(palavra[10:23]) # pegando do 10 ao 23

# pegando a posição do CPF

 cpf  = str('123.254.562-90')

 print(cpf)
 print(cpf[0:7])  # pegando os 6 primeiros dígitos
 print(cpf[12:14]) # pegando os 2 digitos finais

