# -*- coding: utf-8 -*-
"""ScripPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d_6dkniX-_a5TlG5MoBxYH95g3CRI-Rd

# 1° Seção

Vamos criar nosso primeiro código
"""

nome = "Aironys Garrido"
idade = 32
cargo = "Analista de Dados"

print(nome)
print(idade)
print(cargo)

print("Meu nome é:", nome, "Tenho:", idade, "Anos", "Trabalho atualmente com:", cargo )

"""# Módulo 1 - Programação em Python

<p> Nesso módulo vamos estudar a sitaxe nativa de python </p>

<h3> O que é Python </h3>
<p> Python é uma linguagem de programação popular. Foi criado por Guido van Rossum e lançado em 1991.
 </p> <br> 
<h3> Pyhon podo ser usado para: </h3>
<ol> 
  <li>
    Inteligência Artificial
  </li>
  <li>
    Machine learning
  </li>
  <li>
    Desenvolvimento de Software
  </li>
  <li>
    Desenvolvimento de Aplicativos
  </li>
  <li>
    Automações (RPA)
  </li>
  <li>
    IoT (Internet das coisas)
  </li>
  <li>
    Muitas outras
  </li>
<ol>

# 1. Sintaxe básica

<li>Podemos ultilizar (aspas simples) </li>
<li>Podemos ultilizar (aspas duplas) </li>
<li>Podemos ultilizar (\n) para pular uma linha </li>
<li>Podemos ultilizar (#)  para comentar algo</li>
"""

print("Vamos programar em python")

print("Bora estudar")

# Aqui é um comentário

''' 
Comentário em bloco
'''

print('Pulando uma linha  \n  linha a baixo')

"""# 2. Operadores matemáticos

<ol>
  <li>Soma</li>
  <li>Subtração</li>
  <li>Multiplicação</li>
  <li>Divisão</li>
  <li>Exponenciação</li>
  <li>Resto da divisâo</li>
  <li>Divisão de Chão</li>
</ol>
"""

10 + 25

15 - 25

# Exponenciação
4 * 5

15 / 5

2 ** 3

# Resto da divisão
5 % 8

# Resto da divisão
10 % 2

# Resto da divisão
10 % 3

#Divisão de Chão
10  // 2

"""# 3. Variáveis

*   Variáveis são conteiners para armazenar valores de dados
*   Uma variável é criada no momento em que você atribui um valor a ela
"""

# Variáveis

nome = "Aironys"

nome

sobrenome = "Garrido de Macedo"

print(nome, sobrenome)

print('Meu nome completo é: \n', nome, sobrenome)

idade = int(32) 
peso = float(75.5)

print("Minha idade é:",idade)
print("Eu peso", peso)

"""# 4. Tipos de Dados

1.   Listas - São criadas usando [] (Colchetes)
2.   Tuplas - São criadas usando () (Parenteses)

1.   Dicionário - São criadas usando {} (Chaves)

    Esses tipos podem receber qualquer tipo de informação, inclusive operações aritiméticas
"""

lista1 = [15,20,5,7,1,9]

print(lista1)

lista2 = [10, 'Palmeiras', True, False, [522], {completo:'Aironys Garrido'}]

print(lista2)

lista2[3]

lista2[5]

